version: '3.6'

services:
  simulator:
    build:
      dockerfile: dev.Dockerfile
      context: .
    volumes:
    - .:/app
    ports:
    - 8081:8081
    entrypoint: yarn run concurrently -n server,browser --kill-others "node /app/dist/server.js" "DEBUG=cypress:* cypress run --browser chrome /app/dist/browser.js"
