version: '3.6'

services:
  runner:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
    - .:/app
    ports:
    - 8081:8081
    entrypoint: cypress run --browser chrome /app/dist/browser.js
